-- ============================================================
-- V1: 初始表结构（TaskFlow 任务待办）
-- 刻意使用标准 SQL 子集：PostgreSQL(生产) 与 H2-PG模式(本地) 均可直接执行
-- ============================================================

create table if not exists tf_user (
    id         bigint generated by default as identity primary key,
    username   varchar(50)  not null,
    password   varchar(100) not null,
    nickname   varchar(50),
    created_at timestamp    not null default current_timestamp,
    updated_at timestamp    not null default current_timestamp,
    constraint uk_tf_user_username unique (username)
);

create table if not exists tf_todo (
    id          bigint generated by default as identity primary key,
    user_id     bigint        not null,
    title       varchar(200)  not null,
    description varchar(1000),
    status      varchar(20)   not null default 'TODO',
    due_date    date,
    created_at  timestamp     not null default current_timestamp,
    updated_at  timestamp     not null default current_timestamp,
    constraint fk_tf_todo_user foreign key (user_id) references tf_user (id) on delete cascade
);

create index if not exists idx_tf_todo_user_status on tf_todo (user_id, status);
create index if not exists idx_tf_todo_user_due    on tf_todo (user_id, due_date);
